name: 同步qBittorrent仓库

on:
  #schedule:
    #- cron:  '23 6,18 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [mirror, qbittorrent, qbittorrent-beta]

concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/qbittorrent/qBittorrent.git"
          destination-repo: "git@gitee.com:evine/qBittorrent.git"